version: '3.3'

services:
  mongodb:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT:-27017}:27017'
    volumes:
      - 'mongodb:/data/db'

volumes:
    mongodb:
      driver: local